[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor-counter = "3YBAAuxLMjGFUpYZMpJcLb1S2efo4A9v4RdatxvZvp9d"
create-pda = "7LSQrnLwdGvkK1FMHSMuYRJSyVuK6t9kbzqKbSAGoN7K"
hello-world = "9j4hBaQSzLMxdRKdPSveY7fwrPQwdUkvPf99tNyWBcGZ"
king-of-the-hill = "98FYuAg1NBKfSJdDShkY41wg1yBrJaNTgbSgpqcRfzvT"
movie-review = "7yNXF6wFHjHe2QANXwF9qFVyhUW6Th4NAEPzTgqNepcu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
