[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor-counter = "3YBAAuxLMjGFUpYZMpJcLb1S2efo4A9v4RdatxvZvp9d"
create-pda = "7LSQrnLwdGvkK1FMHSMuYRJSyVuK6t9kbzqKbSAGoN7K"
hello-world = "9j4hBaQSzLMxdRKdPSveY7fwrPQwdUkvPf99tNyWBcGZ"
king-of-the-hill = "98FYuAg1NBKfSJdDShkY41wg1yBrJaNTgbSgpqcRfzvT"
solana_practice = "3TiJm6RVQks3ZJ2jYudgN586u51L6vnJjWNGSaCuBG7B"
test-counter = "8n1UxqwGfZFEaMwpLyt5mj9yMBo3m8xtjr5zPwcBVZaZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/dev-wallet.json"

[scripts]
# This command runs typescript tests. The glob pattern 'tests/**/*.ts' 
# matches all .ts files in the 'tests/' directory and any subdirectories.
# The -p flag tells ts-mocha to use a specific file as the project config
# file. The -t flag sets the Mocha timeout to ~16 minutes for long tests.
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
