[package]
name = "clients"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.31.1"
anyhow = "1.0.98"
solana-client = "2.3.5"
solana-sdk = "2.3.1"
tokio = { version = "1.46.1", features = ["full"] }
